# Generated by Django 5.0.6 on 2025-03-31 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта ответа')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильный')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Отношение Курс-Студент',
                'verbose_name_plural': 'Отношения Курсы-Студенты',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacherRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Отношение Курс-Преподаватель',
                'verbose_name_plural': 'Отношения Курсы-Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL Video')),
                ('order_index', models.PositiveIntegerField(verbose_name='Порядок в модуле')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('order_index', models.PositiveIntegerField(verbose_name='Порядок в курсе')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курсов',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='MultiselectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ на задачу с множественными вариантами ответов',
                'verbose_name_plural': 'Ответы на задачи с множественными вариантами ответов',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingTaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Ответ на задачу на программирование',
                'verbose_name_plural': 'Ответы на задачи на программирование',
            },
        ),
        migrations.CreateModel(
            name='RadioAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ответ на задачи с единственным вариантом ответа',
                'verbose_name_plural': 'Ответы на задачи с единственным вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='SelectedOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128, null=True, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ на задачу с которким ответом',
                'verbose_name_plural': 'Ответы на задачи с которким ответом',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('autocheck', models.BooleanField(default=False, verbose_name='Автопроверка')),
                ('type', models.CharField(choices=[('TEST', 'Тест'), ('PROGRAMMING', 'Программирование'), ('SHORT_ANSWER', 'Краткий ответ'), ('FILE_UPLOAD', 'Загрузка файла'), ('TEXT_ANSWER', 'Ответ в виде текста'), ('MULTISELECT', 'Мультиселект'), ('RADIO', 'Один вариант ответа')], max_length=128, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'База Задания',
                'verbose_name_plural': 'Базы Заданий',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('exam', models.BooleanField(default=False, verbose_name='Экзамен')),
                ('order_index', models.PositiveIntegerField(verbose_name='Порядок в модуле')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TestTaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(verbose_name='Порядок в тесте')),
            ],
            options={
                'verbose_name': 'Отношение тест-задача',
                'verbose_name_plural': 'Отношения тест-задача',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=30000, null=True, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ на задачу с текстовым ответом',
                'verbose_name_plural': 'Ответы на задачи с текстовым ответом',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'База ответа',
                'verbose_name_plural': 'Базы ответов',
            },
        ),
    ]
