# Generated by Django 5.0.6 on 2025-03-31 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(through='tags.CourseTag', to='tags.tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='coursestudentrelation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='coursestudentrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', through='courses.CourseStudentRelation', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='courseteacherrelation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courseteacherrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_courses', through='courses.CourseTeacherRelation', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.module', verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='multiselectanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.answer', verbose_name='База ответа'),
        ),
        migrations.AddField(
            model_name='programmingtaskanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.answer', verbose_name='База ответа'),
        ),
        migrations.AddField(
            model_name='radioanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.answer', verbose_name='База ответа'),
        ),
        migrations.AddField(
            model_name='radioanswer',
            name='answer_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.answeroption', verbose_name='Выбранный ответ'),
        ),
        migrations.AddField(
            model_name='selectedoptions',
            name='answer_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.answeroption'),
        ),
        migrations.AddField(
            model_name='selectedoptions',
            name='options_task_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.multiselectanswer'),
        ),
        migrations.AddField(
            model_name='multiselectanswer',
            name='selected_options',
            field=models.ManyToManyField(through='courses.SelectedOptions', to='courses.answeroption', verbose_name='Выбранные ответы'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.answer', verbose_name='База ответа'),
        ),
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='courses.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='testtaskrelation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='testtaskrelation',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='test',
            name='tasks',
            field=models.ManyToManyField(through='courses.TestTaskRelation', to='courses.task'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.answer', verbose_name='База ответа'),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudentrelation',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='courseteacherrelation',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('module', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='selectedoptions',
            unique_together={('answer_option', 'options_task_answer')},
        ),
        migrations.AlterUniqueTogether(
            name='testtaskrelation',
            unique_together={('test', 'task')},
        ),
    ]
