# Generated by Django 5.0.6 on 2025-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в модуле'),
            preserve_default=False,
        ),
    ]
