# Generated by Django 5.0.6 on 2025-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': 'Отношение крус-тэг', 'verbose_name_plural': 'Отношения крусы-тэги'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
